version: '3.0'
services:
  mongo:
    image: mongo
    ports:
      - 27017:27017 # <1>
    volumes:
      - ./docker-compose-files:/docker-entrypoint-initdb.d # <2>
    environment:
      MONGO_INITDB_DATABASE: chat # <3>
